# Generated by Django 6.0.2 on 2026-03-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='login',
            options={'verbose_name': 'User Login', 'verbose_name_plural': 'User Logins'},
        ),
        migrations.AlterModelOptions(
            name='register',
            options={'verbose_name': 'User Registration', 'verbose_name_plural': 'User Registrations'},
        ),
        migrations.AddField(
            model_name='register',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
